### PR TITLE
Indent code of blocks surrounded with curly braces (fix #119)

### LINKED ISSUE #119: Missing indentation when pressing enter after a '{'
Hi, first of all, thanks for this great plugin. It is so far the best way to work with Haxe on Mac !

I have however a problem with indentation. It may seem like a minor problem, but can be pretty annoying with time:

When pressing enter after writing some condition, function, while loop, with an opening brace, I would expect to have an additional indentation (like any other intellij plugin, or even most of the code editors). But instead, the next line is not indented by one more tab, and each time I have to type de tab myself.

Some illustation:

Expected when pressing enter to move to the next line:

```haxe
if (someCondition) {
    | // <- text cursor indented

```

Current behavior:

```haxe
if (someCondition) {
| // <- text cursor not indented

```

I don't know if this change is difficult to achieve, but fixing this problem will, in my opinion, really improve the coding experience.

I am using the latest plugin build from the ClassHierarchy branch on Mac OS X (I also experience the issue on the Intellij repository's plugin).

### PR DESCRIPTION
**Pull request by jeremyfa**
I didn't tested the code (because I didn't install the whole development environment to work on the plugin) but I believe it will work as it is a very small change :)

### CODE REVIEW

**Comment by EBatTiVo** [comment]
OK.  Thanks.  I'll test it and approve the pull if it works.

**Comment by EBatTiVo** [comment]
Tests well.  I took the change.

**Comment by jeremyfa** [comment]
Great, Thank you! Meanwhile I was trying to set up the project to be able to rebuild intellij-haxe.jar and test it myself. Didn't succeeded yet.

**Comment by as3boyan** [comment]
@jeremyfa I had to do this recently, I can make a short video on how to setup it if you need that

**Comment by jeremyfa** [comment]
@as3boyan That would be great! :D

**Comment by as3boyan** [comment]
@jeremyfa Here you go :D Hope that helps.

**Comment by jeremyfa** [comment]
@as3boyan Thank you! My setup was actually correct already. The only part I was missing was about how the plugin debug works (I didn't understand why a new instance of Intellij was showing up when pressing "run" at the first place. Silly.)

Some more pull requests will probably follow soon ;)

**Comment by as3boyan** [comment]
You are welcome)

**Comment by EBatTiVo** [comment]
So, I've taken both pull requests.  Can we close this now?

**Pull request merged**
