### PR TITLE
Add cli test build and run

### PR DESCRIPTION
**Pull request by yanhick**
This uses Ant and a couple shell scripts. You need Ant and oracle jdk installed to run the it, I'll document all of this in the readme. The .travis.yml file takes care of installing build dependencies for Travis.ci.
Locally, you can run ./travis.sh to build and run the tests.

notes:
- We might want to get rid of the shell script eventually and use Ant to fetch the idea sdk in order to make it work on Windows.
- I tried to remove all unecessary cruft from the Ant file, which is already pretty busy for just running tests. Someone with better knowledge of Ant might be able to simplify this.

### CODE REVIEW

**Comment by EBatTiVo** [comment]
@yanhick - I'm not sure whether you just have this open for review or whether you're ready to pull it.  Go ahead and complete the pull yourself, if it's ready.

**Comment by yanhick** [comment]
It's ready, I was waiting for your review, thanks

**Comment by as3boyan** [comment]
Great, so it works now?

**Comment by yanhick** [comment]
Yes,
I was able to use it to build on Travis.ci with my own fork. I'm going to
finish automating the stack (building the jar and the parsers) before I
activate Travis.ci on this repo and I'll update the readme with build steps.

2015-03-13 11:04 GMT-07:00 as3boyan <notifications@github.com>:

**Pull request merged**
