### PR TITLE
Build 13 and 14 from cli

### PR DESCRIPTION
**Pull request by yanhick**
I think that's it. The diff is ridiculously long because of moved files from ```src``` to ```src/common``` but with it, I can run ```make test && IDEA_VERSION=14.0.1 make test``` to build multiple versions.

One thing to keep in mind though is that changing the source structure is probably going to break building from Intellij. I think it would be better if @EBatTiVo or @sganapavarapu1 prepare the fix for building from intellij before merging to master, so that you don't get blocked on your next pull.

### CODE REVIEW

**Comment by EBatTiVo** [comment]
OK.  I'll try it later this week.

**Comment by EBatTiVo** [comment]
So, the change list is long because the files were *copied*; the old ones still exist.  The old ones need to be deleted so that git can figure out that these were just moved files.  That will ease later pulls (if any) from old forks -- and merges for changes people are keeping in their own forks but not sending up to us.

Please start over to get the moves correctly.  It's my understanding that adds and deletes must appear in the same commit to be identified as moves.  If you just delete old files now (on this branch), the version histories (and the old locations of the files for PRs) will be destroyed.

Also, the project file (intellij-haxe.iml) is going to have to be extended to know about the common and version-specific directories.  For instance, lines like:
``` 
<sourceFolder url="file://$MODULE_DIR$/src" isTestSource="false" />
```
are going to have to become:
```
<sourceFolder url="file://$MODULE_DIR$/src/common" isTestSource="false" />
<sourceFolder url="file://$MODULE_DIR$/src/$IDEA_VERSION$" isTestSource="false" />
```
as well as similar types of parameterized changes in the project.xml (e.g. "since" and "until" entries, and specialized release notes, if any).

I'll bet that the command-line build still uses the .iml file to find sources, so I'm guessing that we haven't gotten a proper versioned command-line build yet, either.

**Comment by EBatTiVo** [comment]
> I'll bet that the command-line build still uses the .iml file to find sources, so I'm guessing that we haven't gotten a proper versioned command-line build yet, either.

Ah.  I see how the ant task is doing the build; it isn't using IDEA or the .iml file at all, just the javac2 task.  Presumably IDEA uses that internally, but passing all of the arguments from the .iml instead.

**Comment by yanhick** [comment]
Thanks for the feedback, I thought ```git mv``` would delete ```src/com``` but I was mistaken, I'm fixing this and I'll also fix the .iml file

**Comment by EBatTiVo** [comment]
I would have expected git mv to do it as well...  Seems like a bug.

**Comment by yanhick** [comment]
Yep. To be fair I had to do a few funky stuff, such as getting the HaxeReferenceCopyPasteProcessor from the 14master branch, this might have thrown git off somehow.

Anyway I've fixed the commit and you can see it's a lot cleaner in the github diff, nost files are now labeled "File renamed without changes ".

I'll start looking the .iml file doc to see if there are some "IDEA_VERSION" var I could use

**Comment by EBatTiVo** [comment]
With the following .iml change, this code all compiles correctly and builds a jar file that works with Idea 13.  I presume the same will be true with a similar change for Idea14.  Once you get IDEA building using the ant build internally, then we can just include ${idea.version} (or whatever property name you decide upon) and we won't have to special-case the .iml.  I'd prefer not to pull this change until that's all complete.  That said, there's nothing wrong with this change as it sits right now, except that it won't build without the iml changes..

```
diff --git a/intellij-haxe.iml b/intellij-haxe.iml
index 3d13be9..711ab28 100644
--- a/intellij-haxe.iml
+++ b/intellij-haxe.iml
@@ -4,13 +4,14 @@
   <component name="NewModuleRootManager" inherit-compiler-output="true">
     <exclude-output />
     <content url="file://$MODULE_DIR$">
-      <sourceFolder url="file://$MODULE_DIR$/src" isTestSource="false" />
       <sourceFolder url="file://$MODULE_DIR$/gen" isTestSource="false" />
       <sourceFolder url="file://$MODULE_DIR$/testSrc" isTestSource="true" />
       <sourceFolder url="file://$MODULE_DIR$/grammar" isTestSource="false" />
       <sourceFolder url="file://$MODULE_DIR$/testData" type="java-test-resource" />
       <sourceFolder url="file://$MODULE_DIR$/resources" type="java-resource" />
-      <excludeFolder url="file://$MODULE_DIR$/src/com/intellij/plugins/haxe/runner/debugger/JavaPro
+      <sourceFolder url="file://$MODULE_DIR$/src/common" isTestSource="false" />
+      <sourceFolder url="file://$MODULE_DIR$/src/13.1.6" isTestSource="false" />
+      <sourceFolder url="file://$MODULE_DIR$/src/icons" isTestSource="false" />
     </content>
     <orderEntry type="inheritedJdk" />
     <orderEntry type="sourceFolder" forTests="false" />
```

**Comment by EBatTiVo** [comment]
This was merged through PR #237.

**Pull request closed without merging**
