### PR TITLE
Check if module is HaxeModuleType https://github.com/TiVo/intellij-haxe/issues/166

### PR DESCRIPTION
**Pull request by as3boyan**
Check if module is HaxeModuleType
https://github.com/TiVo/intellij-haxe/issues/166

### CODE REVIEW

**Comment by as3boyan** [comment]
https://github.com/TiVo/intellij-haxe/blob/RefactoringPullUpTest/common/src/com/intellij/plugins/haxe/util/HaxeCommonCompilerUtil.java#L99-99

**Comment by sganapavarapu1** [comment]
reviewed & approved - please merge it @as3boyan

**Comment by EBatTiVo** [comment]
@as3boyan - How did you test this?  Do you make a minimal project, or did you use another project that is available on github?

**Comment by as3boyan** [comment]
I opened Haxe plugin project in secondary instance

**Comment by EBatTiVo** [comment]
Hah!  When I tried that, I was getting the project reloading in both instances (both were updating the project files), so I figured that wasn't a usable combination.  I guess I did something wrong.

**Comment by as3boyan** [comment]
No, you did everything right, I think, just maybe it's not necessary to reload project for first instance during debug.

**Pull request merged**
