### PR TITLE
Resolve Extern Enum Values from qualified name Test case for #39

### PR DESCRIPTION
**Pull request by as3boyan**
Resolve Extern Enum Values from qualified name
Test case for #39

### CODE REVIEW

**Comment by sganapavarapu1** [comment]
approved

**Comment by EBatTiVo** [comment]
Interesting.  Any idea why the push build failed, but the pull request didn't?

(Still approved.  Just wondering.)

**Comment by as3boyan** [comment]
@EBatTiVo https://travis-ci.org/TiVo/intellij-haxe/jobs/59286722, IDEA 14 build failed, probably HaxeReferenceCopyPasteProcessor in log may mean that it attempts to build wrong version of this file

**Comment by EBatTiVo** [comment]
Well, yes.  But why did the push build of the branch use the wrong version of the file while the pull request used the correct one?  I guess neither of us knows the answer to that yet.

**Comment by as3boyan** [comment]
It seems like it was using files from pull request branch(with obsolete .travis.ci and build.xml and other)
Because I made a branch before commit with disabled test cases
https://github.com/TiVo/intellij-haxe/tree/7da7828aef85c035db770d1a633d53c0a67a0965

**Pull request merged**
