### PR TITLE
Update version for 14.1.3 in properties

### PR DESCRIPTION
**Pull request by as3boyan**
Update version for 14.1.3 in properties

### CODE REVIEW

**Comment by EBatTiVo** [comment]
Do you mean to have a plugin jar that only supports 14.1.0 and 14.1.1, then another jar for 14.1.3 and later?  Srikanth suggested that, but it seems like a pain.  I guess it's not so big a deal, though.  Just add another property file and a new target to for common.xml to detect the proper version.

**Comment by as3boyan** [comment]
I would suggest support latest only, and probably if you guys still use 13, then it too.

**Comment by as3boyan** [comment]
Also, @EBatTiVo can you run unit tests in 14.1.3? I got some issues

**Comment by EBatTiVo** [comment]
Will do.  It’ll take five minutes.

-Eric

**Comment by EBatTiVo** [comment]
Unit tests all run fine.  This merge is approved.  I'll do the work to get a better compatibility note.

**Comment by as3boyan** [comment]
Thanks. I just got an errors when I try to run unit tests.

**Comment by EBatTiVo** [comment]
By the way, did you do a make from the HEAD this morning, or were you synced to the same point as the rest of the release?  I’m just wondering because there was that extra parsing fix that didn’t make it into the 13.1 and 14.0 builds.

-Eric

**Comment by as3boyan** [comment]
I updated project. (VCS - Update), so it seems like I build it from HEAD

**Comment by EBatTiVo** [comment]
OK.  No problem.

-Eric

**Comment by EBatTiVo** [comment]
Hmm. I guess it was the extra text that caused the upload error.  That's good to know.

**Pull request merged**
