### PR TITLE
Some tweaks for better default builds on OS X.

### PR DESCRIPTION
**Pull request by EBatTiVo**
A few minor tweaks for default builds on Macs.

### CODE REVIEW

**Comment by EBatTiVo** [comment]
@eliasku  Can you please review this?  I think you're the only other person building on a mac at the moment.

**Comment by eliasku** [comment]
Two improvements are checked, all works great.

**Comment by EBatTiVo** [comment]
@eliasku Thanks for the review, Ilya.

**Comment by EBatTiVo** [comment]
BTW, a request for a review does not imply that you have to test it.  Just verify that it makes sense.  :)

**Pull request merged**
