### PR TITLE
Fix debugger hangs and stop extra variable processing.

### PR DESCRIPTION
**Pull request by EBatTiVo**
Fix debugger trying to populate all variables when stopped at a breakpoint.
Suppress display of back-end generated intermediate variables when debugging.
Fix NPE when editing files outside of a project.

### CODE REVIEW

**Comment by EBatTiVo** [comment]
@sganapavarapu1, @bjitivo, please review.

**Comment by bjitivo** [comment]
How much of this is actual diff, and how much is just code reformatting?

**Comment by EBatTiVo** [comment]
Ignore everything in the src/13.1 and src/14.0 trees.  They are just merges of the code from the src/14.1 tree.

The 13.1 reformat was to make the merging and diffing easier.

**Comment by EBatTiVo** [comment]
@bji, In direct answer to your question, 137 lines of code in two files need to be reviewed: src/14.1/com/intellij/plugins/haxe/runner/debugger/HaxeDebugRunner.java, and src/common/com/intellij/plugins/haxe/util/PsiFileUtils.java.

**Comment by sganapavarapu1** [comment]
I reviewed the HaxeDebugRunner in 14.1 branch and PsiFileUtils... changes seem acceptable conceptually. Having said, I did not try to evaluate finer details on behavior of read/write/thread racing conditions that you fixed in collaboration with Bryan Ischo.

**Comment by sganapavarapu1** [comment]
I skipped reviewing the porting applied in 14.0 and 13.1

**Pull request merged**
