### PR TITLE
Bugfix/alias imports

### PR DESCRIPTION
**Pull request by anibyl**
Fix of the #466.

### CODE REVIEW

**Comment by eliasku** [comment]
@anibyl Please add unit-test to cover the issue

**Comment by anibyl** [comment]
@eliasku unused import inspection test added.

**Comment by anibyl** [comment]
@EBatTiVo Anybody here? :)

**Comment by EBatTiVo** [comment]
@anibyl 

Hm?... oh, yes, sure...  mmm hmm....

**Comment by EBatTiVo** [comment]
@anibyl I've merged it.  Can you close and mark the affected bugs?  Thanks.

**Comment by anibyl** [comment]
@EBatTiVo 
Thanks. I closed the issue.
PS: I opened a couple of new little pull-requests, can you please look at them?

**Pull request merged**
