### PR TITLE
Fix #262

### LINKED ISSUE #262: No auto-completion for static methods
Auto-completion is not working for classes with static methods, actually is resolved when you finish typing method call, but while typing it resolves only static properties and fields, but no static methods are showing up. Big slow-down on productivity for new client-code users.

repro:
```
class StaticMethods {
	public static function foo() {}
}

class Main {
	public static function main() {
		//StaticMethods.foo(); // after typing is resolved, this is good
                StaticMethods. // while typing class not resolved (strange behavior)
	}
}
```

image

### PR DESCRIPTION
**Pull request by as3boyan**
Fix #262
We might need some test cases to make sure everything works as expected

### CODE REVIEW

**Comment by EBatTiVo** [comment]
@as3boyan, @romanmikhailov,  Hi guys,  You both have competing change/pull requests here (#264 #265).  Can you both review each other's changes and come to agreement about which is better?  Either change seems reasonable to me, but we probably don't want both.

**Comment by romanmikhailov** [comment]
@as3boyan Viewed your fix. It's seems to retrieve only static functions. Static fields still not displayed.

**Comment by romanmikhailov** [comment]
@as3boyan But my fix not cover Enum autcompletion and not contains test cases fr this issues.

**Comment by romanmikhailov** [comment]
@as3boyan @EBatTiVo My suggestions get both merged pull requests.

**Comment by as3boyan** [comment]
>Static fields still not displayed.

@romanmikhailov Could you please describe steps how to reproduce issue you mentioned, because to me, it seems like my implementation should fix #262, and it seems to me like everything works fine.

**Comment by romanmikhailov** [comment]
> Could you please describe steps how to reproduce issue you mentioned, because to me, it seems like my implementation should fix #262, and it seems to me like everything works fine.

Your fix works fine for case #262 (+ Enum autocompletion) but fails on next example:

```
class StaticMethods {
    public static function foo() {}
    public static var field:Float;
}

class Main {
    public static function main() {
        //StaticMethods.foo(); // after typing is resolved, this is good
        StaticMethods. // produce only foo. field is absent.
    }
}
```

**Comment by as3boyan** [comment]
Thanks for example, I was able to reproduce it

```haxe
class StaticMethods {
    public var field:Float;
}
```

Works fine.

```haxe
class StaticMethods {
    public static var field:Float;
}
```

Doesn't work. Item is not shown in completion, because of

`namedComponent.isStatic()` doesn't works for `HaxeVarDeclarationPart`

**Comment by romanmikhailov** [comment]
@as3boyan I'm close my pull requests. Please add tests for fields and enum.

**Comment by romanmikhailov** [comment]
@as3boyan Maybe will be better to make your check from `AbstractHaxeNamedComponent.isStatic` in overriden `HaxeVarDeclarationPartImpl.isStatic`?

**Comment by as3boyan** [comment]
There is already test for enum, I will add test for fields.

>@as3boyan Maybe will be better to make your check from AbstractHaxeNamedComponent.isStatic in overriden HaxeVarDeclarationPartImpl.isStatic?

Maybe, but it seems like, `HaxeVarDeclarationPartImpl` is in `gen` folder, and it seems like it is generated from parser.

**Comment by as3boyan** [comment]
@romanmikhailov Thanks a lot for your help

**Comment by romanmikhailov** [comment]
@as3boyan You are welcome.

**Comment by EBatTiVo** [comment]
@as3boyan @romanmikhailov 
Approved for merge, once the field test is added.

**Comment by as3boyan** [comment]
Test case for static field completion is added 3088efa

**Pull request merged**
