### PR TITLE
Forwarding abstract fields not resolved. Autocomplete don't work for forwarding abstract fields. (issue #447)

### PR DESCRIPTION
**Pull request by bynuff**
Fix issues #447 and #108.

- Forwarding abstract fields resolved inside meta @:forward
- Fields autocomplete inside meta @:forward
- Abstract type with forwarding fields resolved
- Abstract type with forwarding fields autocomplete
- Release notes updated

### CODE REVIEW

**Comment by EBatTiVo** [comment]
@bynuff Thanks for the submission.  How about some unit tests for this new functionality?

**Comment by bynuff** [comment]
@EBatTiVo tests for abstract forwarding added

**Comment by EBatTiVo** [comment]
This code looks OK to me.  I didn't see any issues.  However, I'd like @eliasku to review it, too, because he has more experience in the resolver recently.

**Comment by eliasku** [comment]
@EBatTiVo looks fine.
@bynuff Need to fix release notes sentences from "issue-style" to "what fixed / added"

**Comment by bynuff** [comment]
@eliasku fixed

**Comment by nadako** [comment]
Was this actually released? Because I'm having this issue with latest releases right now:



Which is annoying, because `Null<T>` is also an abstract with `@:forward` in Haxe 4.

**Comment by cmandlbaur** [comment]
Also having this issue with my own abstract that is using `@:forward`.

**Comment by cmandlbaur** [comment]
@nadako Seems like its an issue with abstracts that use typeparams, see #713

**Pull request merged**
