### PR TITLE
Completion for word `super`: handle `super` word like `this` word

### PR DESCRIPTION
**Pull request by as3boyan**
Completion for word `super`: handle `super` word like `this` word
https://github.com/TiVo/intellij-haxe/issues/87

### CODE REVIEW

**Comment by EBatTiVo** [comment]
Approved for merge.  Don't forget to update the release notes in plugin.xml.  Thanks.

**Comment by as3boyan** [comment]
Hmmm, accidentally pushed release notes commit  to https://github.com/TiVo/intellij-haxe/pull/452

**Comment by EBatTiVo** [comment]
@as3boyan No sweat.  If you want to merge this, then just revert it on that branch and push it on this one.  Easy-peasy.

I wouldn't leave the change on that branch or hold up the merge of this PR because it make take a couple more days before Carlos gets back to us there.

**Comment by as3boyan** [comment]
@EBatTiVo how to merge this?

**Comment by EBatTiVo** [comment]
Checkout the master branch:
  $ git checkout master

Get it current:
$ git pull origin master

Check out your work branch:
  $ git checkout FixCompletionForSuperWord

Merge master up into it:
  $ git merge --no-ff master

Fix any merge issues, and ‘git add’ any files you edited, then commit.
  $ git commit

Then push back to github to ensure you’ve got a clean build:
  $ git push origin FixCompletionForSuperWord

Wait for travis results, and make any necessary changes (repeat edit, commit, push) until you get a clean build.  Then merge using either the merge button on the PR, or use the command ilne to merge:

$ git checkout master
$ git merge --no-ff FixCompletionForSuperWord
$ git push origin master

Clean up the PR and delete your branches.

**Comment by as3boyan** [comment]
@EBatTiVo Thanks a lot, I had to edit plugin.xml by hand, IntelliJ IDEA seem to have nice solution for merging, but it was generating some additional commits so I was in doubt

**Pull request merged**
