### PR TITLE
Static auto completion fix #262

### LINKED ISSUE #262: No auto-completion for static methods
Auto-completion is not working for classes with static methods, actually is resolved when you finish typing method call, but while typing it resolves only static properties and fields, but no static methods are showing up. Big slow-down on productivity for new client-code users.

repro:
```
class StaticMethods {
	public static function foo() {}
}

class Main {
	public static function main() {
		//StaticMethods.foo(); // after typing is resolved, this is good
                StaticMethods. // while typing class not resolved (strange behavior)
	}
}
```

image

### PR DESCRIPTION
**Pull request by romanmikhailov**
Problems hide in extracting HaxeVarDefenition part (no field information except name) from HaxeVarDefenition instead returning original  HaxeVarDefenition (needs only for name and statc check) HaxeResolveUtil.getNamedSubComponents.

https://github.com/TiVo/intellij-haxe/issues/262

### CODE REVIEW

**Comment by EBatTiVo** [comment]
@romanmikhailov,  Hi! and thanks for your help.  I must be missing something, though, because this change seems to introduce a boolean variable that is set to true in all cases, and checked once (if (<true> && ...)).  Since it is always true, there is no functionality change that I can see.  Can you explain how this change fixes the problem?

**Comment by romanmikhailov** [comment]
Exuse my mistake. Not full push.

**Comment by as3boyan** [comment]
Hi Roman! Thanks for help, are you sure that it's a fix for #262? Because it was reported that completion for methods was not shown. Your fix seems to be related to fields.

**Comment by romanmikhailov** [comment]
@as3boyan Hi. It's fix for both methods and fields autocompletion.

**Comment by romanmikhailov** [comment]
Closed as already implemented in https://github.com/TiVo/intellij-haxe/pull/265

**Pull request closed without merging**
