### PR TITLE
Release v0.10.0 (IDEA16 + fixes)

### PR DESCRIPTION
**Pull request by eliasku**
v0.10.x plugin versions are for IDEA 16 version only. Plugin v0.9.x is for IDEA 14/15.

Beta release for testing: https://github.com/eliasku/intellij-haxe/releases/tag/v0.10.0-beta

Fixes for IDEA 16:
- (CRITICAL) Fixed crash on MACRO_CLASS_LIST assert

Just new fixes:
- Fixed creating classes in TEST source roots
- Fixed debug Flash on Haxe-compiler targe
- Optimize Imports... (issue #471)
- @:deprecated support (issue #459, #473)

Already merged PRs:
- https://github.com/TiVo/intellij-haxe/pull/472
- https://github.com/TiVo/intellij-haxe/pull/474

### CODE REVIEW

**Comment by eliasku** [comment]
@EBatTiVo any news?

**Comment by cmandlbaur** [comment]
Is this repo still active? Seems like last commit was a while ago and this seems like a pretty decent update just waiting some attention.

**Comment by EBatTiVo** [comment]
Yes, it's active -- just less so than before.

I'm working on a version of this PR right now that does not require dropping support for earlier versions.

**Comment by EBatTiVo** [comment]
Hand merged with #484.

**Pull request closed without merging**
