### PR TITLE
fixes #168 and more:

### LINKED ISSUE #168: "update()" in FlxState are "unresolved symbols"
see https://groups.google.com/forum/#!msg/haxeflixel/gGmJ_B3x6tQ/Dxltcsvsi7sJ

we can reproduce the bug by open structure view for Bar.hx with the following code:

//file Foo.hx
```
class Foo { }
```

//file Col.hx
```
class Col<T> {
    var iiii: Int;
}
```
//file Bar.hx
```
class Bar extends Col<Foo> {
    var ssss: String;
}
```

Note that, if we put all class in one file then structure view will show Col as super class of Bar but if put each class in one file then structure view (for Bar.hx) will NOT show Col.

### PR DESCRIPTION
**Pull request by giabao**
fixes #168 and more:
+ Can't resolve class in same package that is defined in a different module (.hx file)
+ Must resolve class in the same package (if any) before try resolving class (same name) in defaul (empty) package
+ also change in HaxeResolveUtil.getQName(PsiElement, boolean):
    - change public -> private, add @Nullable annotation,  remove `boolean searchInSamepackage` param.
    - check usingStatement.getReferenceExpression() != null before call .getText()
    - remove some unused local variables, remove checking `if (element != null)` because (IDEA warning) it is always true

### CODE REVIEW

**Comment by giabao** [comment]
Use the code below (each class in a separated file) to manually test the issue & the fix:

```haxe
package foo;
class Foo { }

package foo;
class Col<T> {
    var iiii: Int; //with code change in PR #169, `Int` is unresolved 
}

package foo;
//Foo must be resolved to foo.Foo
//before fix, Foo is unresolved symbol
class Bar extends Col<Foo> {
    var ssss: String;
}

package ;
class Foo { }

package foo2;
import foo.Col;

//Foo must be resolved to class Foo in empty package, not foo.Foo
class Bar extends Col<Foo> {
    var ssss: String;
}
```

I have tried to create a automatic test suite by seeing [this guide](https://confluence.jetbrains.com/display/IDEADEV/Testing+IntelliJ+IDEA+Plugins) & testData, testSrc directory but found its too hard :(

**Comment by as3boyan** [comment]
I think if reference.resolve() != null, then it should be ok.

**Comment by giabao** [comment]
@as3boyan Sorry. Can you explain more detail?

**Comment by as3boyan** [comment]
@giabao 
1. Create a folder in `testData` directory, with a name corresponding to brief description of functionality you would like to test, for example create folder `resolveClassInSamePackage`
2. Navigate to `testSrc` and create some Java file in perhaps `ide` subfolder, it should end with `Test` if I recall correctly.
3. Open that test file(Java). Look at https://github.com/TiVo/intellij-haxe/blob/master/testSrc/com/intellij/plugins/haxe/actions/HaxeFindUsagesTest.java#L31-31
4. Make sure your test file extends `com.intellij.plugins.haxe.HaxeCodeInsightFixtureTestCase`
5. Create a function like
```java
  public void testVarDeclaration() throws Throwable {  //VarDeclaration item will be shown in Console as test case
    myFixture.configureByFiles("VarDeclaration.hx", "com/bar/Foo.hx"); //Files on which you want to test
    doTest(0); //Here get psi file, using some PsiManager or what, and try to resolve reference, for example when you get PsiFile, you may find reference using `PsiTreeUtil.findChildOfType`, then attempt to call resolve and check if it's not null (assertTrue(reference.resolve() != null))
  }
```

@EBatTiVo If that is clear, perhaps we can add this(or better version) to CONTRIBUTING or README, and would be nice if users could add such cases

**Pull request merged**
