### PR TITLE
Allow `extern` to be used as package

### PR DESCRIPTION
**Pull request by as3boyan**
Allow `extern` to be used as package

### CODE REVIEW

**Comment by EBatTiVo** [comment]
Will this work in the case of `import myclass.extern`?  My guess is that it only works when extern is followed by a space, but not preceded by one.  Can we fix that by preceding the token by a whitespace character?

Another thought: Within a lexer context, do regular expressions work differently (i.e. do space tokens "[\ ]" infer other types of whitespace, or is the keyword now going to be broken if the code looks like:
```
    private extern\n
    function doSomething() {}
```
?

**Comment by as3boyan** [comment]
It should work in that case, because import ends with `;`, if not - then it will be highlighted. Perhaps, http://stackoverflow.com/questions/13317319/regular-expressions-maching-whitespaceflex

Maybe we can add some color highlighting rules for such words, but this can make things more complicated, for example `public`, `extern` and others will be treated as IDs...

**Comment by EBatTiVo** [comment]
In thinking about this a bit, this looks like we're going to get ourselves into more work no matter what we do.  If we change keywords to require whitespace just prior and/or just after, then we break the cases where they occur immediately following braces, etc.  (e.g. if we changed the definition for 'var' to include a space before and/or after, then we'll change how "{var a=1;}" is handled.

Can we find a way to know if an ID is expected at a given position, and, if it is, change the (AST) token type from keyword to ID or create an ID token in the first place?

**Comment by as3boyan** [comment]
I'm not sure that trick with whitespaces will work for `var extern = "test"`. It's quite rare to declare variables with such names.

I think parser can just match text without keywords(seems like it works for `as`), not sure about performance. Then we can dynamically highlight keywords if they put in proper places.

**Comment by as3boyan** [comment]
It's funny but I found something like this
https://github.com/HaxeFoundation/haxe/commit/3d8cb52fa8624faf1aa1854f09c108d1593e78ee

**Comment by as3boyan** [comment]
Perhaps HaxeASTFactory can do something on AST level

**Comment by EBatTiVo** [comment]
Approved for pull.  It may not be the best solution, but it's a reasonable one for the time being.  Fixing this at the PSI level is likely non-trivial.

**Comment by as3boyan** [comment]
Is there is an easy way to merge this? Using some software maybe? Only 1 file needs to be changed

**Comment by EBatTiVo** [comment]
Use the git command line.  The link below the "We can't automaically merge this pull request" message lays it out in easy steps.

There is no automatic way of merging after there are conflicts.

**Comment by as3boyan** [comment]
I think there should be some way like in IntelliJ IDEA when we update project, when merging we can select which version should remain.

**Comment by EBatTiVo** [comment]
> I think there should be some way like in IntelliJ IDEA when we update project, when merging we can select which version of file should remain.

Go read this:  http://2ndscale.com/rtomayko/2008/the-thing-about-git   When you're done, you will understand that git can do exactly what you asked.

**Comment by as3boyan** [comment]
Thanks, that's great article.
Sorry, I made too much commits for merge.

Got an idea for `extern` keyword
`extern[\ ] private? (class|interface|enum)`
Might be performance intensive, not sure.

**Pull request merged**
