### PR TITLE
Generated code from haxe.bnf file.

### PR DESCRIPTION
**Pull request by bynuff**
- generated code from current haxe.bnf file
- fix differences in source code after generation

### CODE REVIEW

**Comment by bynuff** [comment]
@EBatTiVo ci fixed in #524 PR by @SlavaRa

**Comment by EBatTiVo** [comment]
@bynuff Why did you find this change necessary?  #517 (already merged into master) also rebuilt the haxe.bnf output.  Did that have issues on your machine?  If so, what version of grammar-kit are you using?

I was about to pull in #522 which gets rid of the gen tree altogether and, thus, requires the gen tree to be rebuilt with every build cycle.  If the generated output is inconsistent, then we might have to abandon that plan.

**Comment by bynuff** [comment]
@EBatTiVo I try to use 1.2.1 and 1.4.1 versions grammar-kit. In both cases I got changes in generated code. What kind version of grammar-kit needs to be used? In future I want make some changes in bnf to fix highlighting in typedefs with multiple extensions.

**Comment by EBatTiVo** [comment]
@bynuff We are using grammar-kit 1.2.0.  It works with, and produces identical code for, all versions of IDEA 14.0 through 2016.3.  If you are willing, you can try using the RemoveGenTreeFromSourceBase branch, which ensures that the proper version of grammar-kit is available and uses it.  If it doesn't work for you, then let me know.  -- Or I can just merge it and you can file a new bug.

**Comment by bynuff** [comment]
@EBatTiVo Yes, you are right. With version 1.2.0 is all ok. I think no sense in this PR.

**Pull request closed without merging**
