### PR TITLE
Disable Travis CI email notifications

### PR DESCRIPTION
**Pull request by as3boyan**
Disable Travis CI email notifications

### CODE REVIEW

**Comment by as3boyan** [comment]
Currently it's not really helpful.

**Comment by EBatTiVo** [comment]
Yeah, OK for now.  We'll re-enable it when the unit tests are all fixed.  (We're down to 6 now, besides the ones that need updating for the comment fix.)

**Comment by EBatTiVo** [comment]
Sorry, I should have said "approved for pull."

**Comment by as3boyan** [comment]
No problem, I got it

**Pull request merged**
