### PR TITLE
Disable failing unit tests so that we can see new failures.

### PR DESCRIPTION
**Pull request by EBatTiVo**
@yanhick, @sganapavarapu1, 

Hi guys.  I've disabled all failing unit tests and made all tests continue in the face of failure like we talked about this morning.  I'd like to merge this one first, then work on getting the AntBuildsFromWithinIdea and build-13-and-14-from-CLI branches merged into a single branch for pulling tomorrow.

### CODE REVIEW

**Comment by sganapavarapu1** [comment]
in build-text.xml, on line 114 ... why is showoutput="yes" changed to showoutput="no" ... 
how does that impact?

Everything else looks great.

**Comment by EBatTiVo** [comment]
> in build-text.xml, on line 114 ... why is showoutput="yes" changed to showoutput="no" ... 
how does that impact?

It stops the output from going to Ant's logging system *in addition to* the output formatters.  It always goes to the formatters, and formatted output is what we're getting in the output logs.  So, this just stops some extra logging going to a file that we don't see.

**Comment by EBatTiVo** [comment]
BTW, I tried using @Ignore, but the Junit that's installed on my Ubuntu installation (14.04 LTS) isn't the shiny new 4.0 version.  Also, the version that's installed with IDEA is not 4.0 yet, either, so while I can set the @Ignore and @Test flags, they are ignored and the tests still run.

**Comment by sganapavarapu1** [comment]
I'm okay with 'not' using @Ignore for now (as this is only for 5-6 tests, that are already in process of being fixed).

Approved for commit/merge.

**Pull request merged**
