### PR TITLE
Highlight 'in' as keyword when it appears in a for statement.

### PR DESCRIPTION
**Pull request by EBatTiVo**
( Issue #501)

OK.  I started by trying to answer the question of why this wasn't working and where it had to be fixed.  I ended with the fix.  

However, I also spent quite a bit of time trying to make a unit test for this and have failed.  There are no other color tests that I can find (even on other projects).  The existing annotation tests for the plugin expect and check for error annotations and don't work for coloring (well... the ones I tried to write all work when they should be failing).

### CODE REVIEW

**Comment by eliasku** [comment]
What do you think to make keywords highlighting on global level?

For example in this PR we are missing `in` for `import .. in ..;` statement.

image

And I think `from`, `to`, `in` are not allowed for identifiers as well, so maybe we should fix that on the lexer level? and these words will be tracked by IDEA as keywords automatically?

**Comment by EBatTiVo** [comment]
So, `from` and `to` are always used as @: modifiers, right?  At least, that's all I found in the Haxe manual, but I could easily have missed something.  As far as not being allowed as identifiers, I don't know about that.

If they are truly not allowed as identifiers, we could write a rule something like is already used for *Statement in the BNF.  That would create a new PSI element type that we could test for, but it's still the same code that would do the highlighting.

At any rate, highlighting is a hint.  What you really want is for the misused keyword to be marked as an error.  That will require changing the semantic annotator.

**Comment by eliasku** [comment]
For  there are general metas for Haxe `@:from` and `@:to`.
I'm talking about keywords:
`abstract ShortVec2(Int) to Int from Int {` - here `to` and `from` are keywords.

Here you could find all keywords used for Haxe language:
https://haxe.org/manual/expression.html#keywords

**Comment by EBatTiVo** [comment]
If what you are asking is whether we should be adding new rules like:
inKeyword ::= 'in'
asKeyword ::= 'as'
toKeyword ::= 'to'
fromKeyword ::= 'from'

I can see how that would be useful.  But just doing those words seems piecemeal.  The BNF is littered with keywords that aren't defined as such.  We could convert them all and, if we do, it will be quite a task.  (Actually, it's harder to review than anything.)  I'm not convinced, yet, that it's worthwhile.

**Comment by eliasku** [comment]
I think now PR looks good and makes the most related things done.
But in my opinion that later we should start updating BNF. When we will have enough time :)

**Pull request merged**
