### PR TITLE
Update copyrights.

### PR DESCRIPTION
**Pull request by EBatTiVo**
Auto-update the /gen copyrights for 2016 so that actual changes will be isolated.

### CODE REVIEW

**Comment by EBatTiVo** [comment]
I'm going to pull this even though CI failed because this is; a) just comments; and b) The build is failing because one of the versions of IDEA that CI is building against is no longer available where it used to be.  The CI scripts have to be updated, but that's a different pull request.

**Comment by as3boyan** [comment]
Thanks)

**Comment by EBatTiVo** [comment]
You’re welcome.

I made a different set of changes that I think you’ll like.  I don’t have them tested yet, but let me post them for you to look at…

Also, what did you do to test the change?

-Eric

**Comment by as3boyan** [comment]
You mean https://github.com/TiVo/intellij-haxe/pull/384 ? It is ok, about my changes - I run a unit tests, that's all, `echoed` property.file, also how do you enable echo level to "debug")

**Comment by EBatTiVo** [comment]
> also how do you enable echo level to "debug"?

Where do you mean, in the ant files?  add '-debug' to the ant command line.

**Pull request merged**
